<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use AppBundle\Entity\Article as article;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getNavBar()
    {
        return $this->createQueryBuilder('c')
            ->addOrderBy('c.position', 'ASC')
            ->getQuery()->getResult();
    }

    public function getCategoriesByUser($user = null)
    {
        $builder = $this->createQueryBuilder('c');
        $sql = $builder
            ->select(array('COUNT(a) AS nbArticles', 'c.color', 'c.position', 'c.name'))
            ->innerJoin('AppBundle\Entity\Article', 'a', 'WITH', 'c.id = a.category');
        if (!is_null($user)) {
            $sql = $builder->andWhere('a.user = :userId')
                ->setParameter('userId', $user->getId());
        }
        $sql = $builder->groupBy('c.color', 'c.position', 'c.name')
            ->addOrderBy('c.position', 'ASC')
            ->getQuery()->getResult();

        return $sql;
    }
}
