<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getNavBar()
    {
        return $this->createQueryBuilder('c')
            ->addOrderBy('c.position', 'ASC')
            ->getQuery()->getResult();
    }
}
