<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCommentsByArticle(Article $article)
    {
        return $this->createQueryBuilder('c')
            ->where('c.hidden <= 0')
            ->andWhere('c.article = :articleId')
            ->setParameter('articleId', $article->getId())
            ->addOrderBy('c.dateCreated', 'DESC')
            ->getQuery()->getResult();
    }
}
