<?php

namespace AppBundle\Repository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList()
    {
        return $this->createQueryBuilder('s')
            ->addOrderBy('s.createdAt', 'DESC')
            ->getQuery()->getResult();
    }
}
