imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    analytics:
      id_account: flareup-1327@appspot.gserviceaccount.com
      id_key: 78fdbdd326cce22b53b9be1333aa87113b805f1b
      id_view: 122912967
      name_file: FlareUp-78fdbdd326cc.p12

framework:
    #esi:             ~
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ga_tracking: UA-78515324-1

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS User Bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
#    registration:
#        form:
#            type: app_fos_user_register
#            validation_groups: [Register, Default, Registration]
#        confirmation:
#            enabled: true
#            template: AppFrontOfficeBundle:Registration:email.html.twig
    profile:
        form:
            type: app_fos_user_profile
            #validation_groups: [Profile, Default]
    resetting:
        email:
            template: AppFrontOfficeBundle:Resetting:email.html.twig
    group:
        group_class: App\MainBundle\Entity\Group
    from_email:
        address: s.feasson@gmail.com
        sender_name: syfea

assetic:
    debug: "%kernel.debug%"
    use_controller: "%kernel.debug%"
    bundles: []
    filters:
        cssrewrite: ~

genemu_form:
    tinymce:
        script_url: '/bundles/app/js/tinymce/jquery.tinymce.min.js'
        enabled: true
        theme:   advanced
    recaptcha:
        public_key:  '6Lej9iATAAAAAB3fQC4RNSMLDuOuJyholKy8snSj'
        private_key: '6Lej9iATAAAAAHPloNEPmSn0uO7FHInTshmzGSYq'
        validation:
            host: www.google.com
            port: 80
            path: /recaptcha/api/verify
            timeout: 10
            code: ~
        configs: []

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers: ['html_purifier']
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    #external_plugins: ['youtube']
    toolbar_groups:
        document: []
        clipboard: ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo']
        editing: []
        links: ['Link','Unlink','Anchor']
        basicstyles: ['Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat']
        paragraph: ['NumberedList','BulletedList','-','Outdent','Indent','-','JustifyLeft', 'JustifyCenter','JustifyRight','JustifyBlock']

        insert: ['Image','Table','HorizontalRule']
        styles: ['Styles','Format']
        tools: ['Maximize', 'ShowBlocks']
    ui_color: '#000000'
    startup_outline_blocks: true
    width: 100% #Integer or %
    height: 500 #Integer or %
    language: 'en-au'
    filebrowser_image_browse_url:
            route: elfinder
            route_parameters:
                 instance: ckeditor


fm_elfinder:
    instances:
        ckeditor:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to manage loading of javascript and css assets manually
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/article_content
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        attributes:
                            - { pattern: '/(.*?)/', read: true, write: true, locked: true }