app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# FOS USER BUNDLE ROUTES
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password


# BACKOFFICE BUNDLE
app_back_office:
    resource: "@AppBundle/Resources/config/routing_bo.yml"
    prefix:   /backoffice

# FRONTOFFICE BUNDLE
app_front_office:
    resource: "@AppBundle/Resources/config/routing_fo.yml"
    prefix:   /mon-compte

# CMS BUNDLE
app_cms:
    resource: "@AppBundle/Resources/config/routing_cms.yml"
    prefix:   /

# REGISTRATION
fos_user_registration_register:
    pattern: /inscription
    defaults: { _controller: FOSUserBundle:Registration:register }
    requirements:
        _method: GET|POST

fos_user_registration_check_email:
    pattern: /inscription/e-mail
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    requirements:
        _method: GET

fos_user_registration_confirm:
    pattern: /inscription/confirmation/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    requirements:
        _method: GET

fos_user_registration_confirmed:
    pattern: /inscription/confirmation
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
    requirements:
        _method: GET

# RESETTING PASSWORD
fos_user_resetting_request:
    pattern: /mot-de-passe-oublie/reinitialisation
    defaults: { _controller: FOSUserBundle:Resetting:request }
    requirements:
        _method: GET

fos_user_resetting_send_email:
    pattern: /mot-de-passe-oublie/e-mail
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }
    requirements:
        _method: GET|POST

fos_user_resetting_check_email:
    pattern: /mot-de-passe-oublie/verification
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }
    requirements:
        _method: GET

fos_user_resetting_reset:
    pattern: /mot-de-passe-oublie/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }
    requirements:
        _method: GET|POST

app_article_fo_display:
    path: /article/{id}/{name}
    defaults: { _controller: "AppBundle:Article:display" }
    requirements:
      name: "[a-zA-Z0-9-]{2,500}"

app_category_fo_display:
    path: /category/{id}/{name}
    defaults: { _controller: "AppBundle:Category:display" }
    requirements:
      name: "[a-zA-Z0-9-]{2,500}"

app_user_fo_display:
    path: /user/{id}/{name}
    defaults: { _controller: "AppBundle:User:display" }
    requirements:
      name: "[a-zA-Z0-9-]{2,500}"

app_ajax_subscriber_save:
    path: /subscriber/save
    defaults: { _controller: "AppBundle:Subscriber:save" }
    requirements:
      _method: POST

app_ajax_comment_save:
    path: /comment/save
    defaults: { _controller: "AppBundle:Comment:save" }
    requirements:
      _method: POST

app_default_homepage:
    path: /
    defaults: {_controller: AppBundle:Default:index}

app_contact_general:
    path: /contact
    defaults: {_controller: AppBundle:Contact:index}

route_name:
  path: /web/uploads/articles

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
