app_backofficebundle_home:
    pattern: /
    defaults: { _controller: "AppBundle:BackOffice:index" }
    requirements:
        _method: GET

app_backofficebundle_myaccount:
    pattern: /my-account
    defaults: { _controller: "AppBundle:BackOffice:myaccount" }
