app_backofficebundle_home:
    path: /
    defaults: { _controller: "AppBundle:BackOffice:index" }
    requirements:
        _method: GET

app_backofficebundle_users:
    path: /users
    defaults: { _controller: "AppBundle:User:index" }
    requirements:
        _method: GET

app_backofficebundle_myaccount:
    path: /my-account
    defaults: { _controller: "AppBundle:BackOffice:myaccount" }

app_backofficebundle_user_create:
    path: /user/create
    defaults: { _controller: "AppBundle:User:create" }

app_backofficebundle_user_update:
    path: /user/{id}/update
    defaults: { _controller: "AppBundle:User:update" }

app_backofficebundle_user_delete:
    path: /user/{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }

app_backofficebundle_category_index:
    path: /categories
    defaults: { _controller: "AppBundle:Category:index" }

app_backofficebundle_category_create:
    path: /category/create
    defaults: { _controller: "AppBundle:Category:create" }

app_backofficebundle_category_update:
    path: /category/{id}/update
    defaults: { _controller: "AppBundle:Category:update" }

app_backofficebundle_category_delete:
    path: /category/{id}/delete
    defaults: { _controller: "AppBundle:Category:delete" }

app_backofficebundle_article_index:
    path: /articles
    defaults: { _controller: "AppBundle:Article:index" }

app_backofficebundle_article_create:
    path: /article/create
    defaults: { _controller: "AppBundle:Article:create" }

app_backofficebundle_article_update:
    path: /article/{id}/update
    defaults: { _controller: "AppBundle:Article:update" }

app_backofficebundle_article_delete:
    path: /article/{id}/delete
    defaults: { _controller: "AppBundle:Article:delete" }