app_backofficebundle_home:
    pattern: /
    defaults: { _controller: "AppBundle:BackOffice:index" }
    requirements:
        _method: GET

app_backofficebundle_users:
    pattern: /users
    defaults: { _controller: "AppBundle:User:index" }
    requirements:
        _method: GET

app_backofficebundle_myaccount:
    pattern: /my-account
    defaults: { _controller: "AppBundle:BackOffice:myaccount" }

app_backofficebundle_user_create:
    pattern: /user/create
    defaults: { _controller: "AppBundle:User:create" }

app_backofficebundle_user_update:
    pattern: /user/{id}/update
    defaults: { _controller: "AppBundle:User:update" }

app_backofficebundle_user_delete:
    pattern: /user/{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }