services:
    user.form.profile.type:
        class: AppBundle\Form\Type\ProfileType
        parent: fos_user.profile.form.type
        tags:
            - { name: form.type, alias: app_fos_user_profile }

    app_ckeditor.transformer.remove_images:
        class: AppBundle\Transformer\RemoveImages
        tags:
            - { name: trsteel_ckeditor.transformer, alias: remove_images }